# -*- coding: utf-8 -*-
"""student-00-7b6cde9b0dca (Mar 27, 2026, 10:02:44 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/repositories/239eec24-35da-4882-88a3-6ac550bd2633
"""

pip install --upgrade google-cloud-bigquery google-cloud-storage vertexai requests pandas

from google.cloud import bigquery
from google.cloud import storage

PROJECT_ID = "qwiklabs-gcp-01-bb0d31ab0812"
DATASET_ID = "aero_alerts"
TABLE_ID = f"{PROJECT_ID}.{DATASET_ID}.airports"
SOURCE_URI = "gs://labs.roitraining.com/data-to-ai-workshop/airports.csv"

client = bigquery.Client(project=PROJECT_ID)

# Create dataset if it doesn't exist
dataset = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
dataset.location = "US"
client.create_dataset(dataset, exists_ok=True)

# Load CSV directly from GCS to BigQuery
job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.CSV,
    skip_leading_rows=1,
    autodetect=True,
)

load_job = client.load_table_from_uri(SOURCE_URI, TABLE_ID, job_config=job_config)
load_job.result()  # Wait for completion
print(f"Loaded {client.get_table(TABLE_ID).num_rows} rows into {TABLE_ID}.")

alerts_df = pd.DataFrame(alerts_data)
alerts_table_id = f"{PROJECT_ID}.{DATASET_ID}.airport_alerts"

# Add this config to tell BigQuery to figure out the column types automatically
job_config = bigquery.LoadJobConfig(
    autodetect=True,
    write_disposition="WRITE_TRUNCATE" # Overwrites the table if it already exists
)

load_job = client.load_table_from_dataframe(
    alerts_df,
    alerts_table_id,
    job_config=job_config
)

load_job.result() # Wait for the job to complete
print(f"Successfully loaded {len(alerts_df)} alerts into {alerts_table_id}")

import pandas as pd
from google.cloud import bigquery
from google.api_core import exceptions

# 1. Ensure you have data
if not alerts_data:
    print("CRITICAL ERROR: 'alerts_data' list is empty. Check your Weather API/Gemini loop above.")
else:
    # 2. Convert to DataFrame and fix 'None' or 'NaN' issues
    alerts_df = pd.DataFrame(alerts_data)
    alerts_df = alerts_df.astype(str)  # Forces all columns to string to avoid type ambiguity

    alerts_table_id = f"{PROJECT_ID}.{DATASET_ID}.airport_alerts"

    # 3. Explicitly define the schema to satisfy the "Empty Schema" error
    job_config = bigquery.LoadJobConfig(
        schema=[
            bigquery.SchemaField("airport_id", "STRING"),
            bigquery.SchemaField("name", "STRING"),
            bigquery.SchemaField("latitude", "STRING"), # Stored as string to match .astype(str)
            bigquery.SchemaField("longitude", "STRING"),
            bigquery.SchemaField("forecast", "STRING"),
            bigquery.SchemaField("ai_alert", "STRING"),
        ],
        write_disposition="WRITE_TRUNCATE", # Replaces table data
    )

    try:
        # 4. Use the Python Client to load the data
        print(f"Attempting to load {len(alerts_df)} alerts into {alerts_table_id}...")
        load_job = client.load_table_from_dataframe(
            alerts_df,
            alerts_table_id,
            job_config=job_config
        )
        load_job.result()  # Wait for job to complete
        print(f"SUCCESS: Loaded {len(alerts_df)} alerts into {alerts_table_id}.")

    except exceptions.BadRequest as e:
        print(f"FAILED: BigQuery rejected the request. Details: {e}")
    except Exception as e:
        print(f"AN UNKNOWN ERROR OCCURRED: {e}")

import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import pandas as pd
import time

# 1. Initialize Gemini
vertexai.init(project=PROJECT_ID, location="us-central1")
model = GenerativeModel("gemini-1.5-flash")
# 2. Get Large US Airports
query = f"SELECT id, name, latitude_deg, longitude_deg FROM `{TABLE_ID}` WHERE type = 'large_airport' AND iso_country = 'US' LIMIT 5"
airports_df = client.query(query).to_dataframe()

# REQUIRED: NWS API needs a User-Agent header
headers = {'User-Agent': '(my-weather-app, myemail@example.com)'}

alerts_data = []

print(f"Starting weather pull for {len(airports_df)} airports...")

for index, row in airports_df.iterrows():
    try:
        # Step A: Get metadata for coordinates
        point_url = f"https://api.weather.gov/points/{row['latitude_deg']},{row['longitude_deg']}"
        res = requests.get(point_url, headers=headers)
        res.raise_for_status() # Check for 403 or 404 errors

        forecast_url = res.json()['properties']['forecast']

        # Step B: Get actual forecast text
        forecast_res = requests.get(forecast_url, headers=headers)
        forecast_res.raise_for_status()

        forecast_text = forecast_res.json()['properties']['periods'][0]['detailedForecast']

        # Step C: Generate AI Alert
        prompt = f"Create a short aviation safety alert for {row['name']}. Weather: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": str(row['id']),
            "name": row['name'],
            "latitude": float(row['latitude_deg']),
            "longitude": float(row['longitude_deg']),
            "forecast": forecast_text,
            "ai_alert": response.text
        })
        print(f"Successfully processed: {row['name']}")

        # Avoid hitting API rate limits
        time.sleep(1)

    except Exception as e:
        print(f"Skipping {row['name']} due to error: {e}")

if not alerts_data:
    print("CRITICAL ERROR: List is still empty. Verify your project has internet access.")
else:
    print(f"Success! Generated {len(alerts_data)} alerts.")



# 5. Save to BigQuery with explicit Schema
if not alerts_data:
    print("Error: No alerts were generated. Check your API/Gemini loop above.")
else:
    alerts_df = pd.DataFrame(alerts_data)
    alerts_table_id = f"{PROJECT_ID}.{DATASET_ID}.airport_alerts"

    # Explicitly define the schema so BigQuery doesn't have to guess
    job_config = bigquery.LoadJobConfig(
        schema=[
            bigquery.SchemaField("airport_id", "STRING"),
            bigquery.SchemaField("name", "STRING"),
            bigquery.SchemaField("latitude", "FLOAT"),
            bigquery.SchemaField("longitude", "FLOAT"),
            bigquery.SchemaField("forecast", "STRING"),
            bigquery.SchemaField("ai_alert", "STRING"),
        ],
        write_disposition="WRITE_TRUNCATE",
    )

    try:
        load_job = client.load_table_from_dataframe(
            alerts_df,
            alerts_table_id,
            job_config=job_config
        )
        load_job.result()  # Wait for completion
        print(f"Successfully loaded {len(alerts_df)} alerts into {alerts_table_id}")
    except Exception as e:
        print(f"Failed to load table: {e}")

import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import pandas as pd

vertexai.init(project=PROJECT_ID, location="us-central1")
model = GenerativeModel("gemini-1.5-flash-001")

# 1. Query large US airports
query = f"""
    SELECT id, name, latitude_deg, longitude_deg
    FROM `{TABLE_ID}`
    WHERE type = 'large_airport' AND iso_country = 'US'
    LIMIT 10  -- Limit for POC
"""
airports_df = client.query(query).to_dataframe()

alerts_data = []

for index, row in airports_df.iterrows():
    try:
        # 2. Get NWS Grid Point
        point_url = f"https://api.weather.gov/points/{row['latitude_deg']},{row['longitude_deg']}"
        res = requests.get(point_url).json()
        forecast_url = res['properties']['forecast']

        # 3. Get Forecast
        forecast_data = requests.get(forecast_url).json()
        periods = forecast_data['properties']['periods'][0] # Current period
        forecast_text = periods['detailedForecast']

        # 4. Generate Alert with Gemini
        prompt = f"System: You are an aviation safety expert. Create a concise, professional weather alert for pilots at {row['name']}. Forecast: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": row['id'],
            "name": row['name'],
            "latitude": row['latitude_deg'],
            "longitude": row['longitude_deg'],
            "forecast": forecast_text,
            "ai_alert": response.text
        })
    except Exception as e:
        print(f"Error processing {row['name']}: {e}")

# 5. Save to BigQuery
alerts_df = pd.DataFrame(alerts_data)
alerts_table_id = f"{PROJECT_ID}.{DATASET_ID}.airport_alerts"
client.load_table_from_dataframe(alerts_df, alerts_table_id).result()

import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import pandas as pd
import time

# 1. USE GEMINI 1.0 PRO - This is the standard for Qwiklabs
vertexai.init(project=PROJECT_ID, location="us-central1")
model = GenerativeModel("gemini-1.0-pro")

# 2. Get Large US Airports
query = f"SELECT id, name, latitude_deg, longitude_deg FROM `{TABLE_ID}` WHERE type = 'large_airport' AND iso_country = 'US' LIMIT 5"
airports_df = client.query(query).to_dataframe()

# REQUIRED for NWS API
headers = {'User-Agent': '(my-weather-app, myemail@example.com)'}
alerts_data = []

print(f"Starting weather pull for {len(airports_df)} airports using gemini-1.0-pro...")

for index, row in airports_df.iterrows():
    try:
        # Step A: Get NWS metadata
        point_url = f"https://api.weather.gov{row['latitude_deg']},{row['longitude_deg']}"
        res = requests.get(point_url, headers=headers)
        res.raise_for_status()
        forecast_url = res.json()['properties']['forecast']

        # Step B: Get actual forecast
        forecast_res = requests.get(forecast_url, headers=headers)
        forecast_res.raise_for_status()
        # Grab the first period forecast
        forecast_text = forecast_res.json()['properties']['periods'][0]['detailedForecast']

        # Step C: Generate AI Alert
        prompt = f"Create a short aviation safety alert for {row['name']}. Weather: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": str(row['id']),
            "name": row['name'],
            "latitude": float(row['latitude_deg']),
            "longitude": float(row['longitude_deg']),
            "forecast": forecast_text,
            "ai_alert": response.text
        })
        print(f"✅ Success: {row['name']}")
        time.sleep(1)

    except Exception as e:
        print(f"❌ Skipping {row['name']} due to error: {e}")

if not alerts_data:
    print("CRITICAL ERROR: List is still empty. Check your internet or API permissions.")
else:
    print(f"DONE! Generated {len(alerts_data)} alerts.")

# --- STEP 3: CORRECTED WEATHER PULL ---
import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import time
import pandas as pd

# Use 1.0 Pro for Qwiklabs compatibility
vertexai.init(project=PROJECT_ID, location="us-central1")
model = GenerativeModel("gemini-1.0-pro")

headers = {'User-Agent': '(my-weather-app, myemail@example.com)'}
alerts_data = []

print("Starting corrected weather pull...")

# Ensure airports_df is ready
query = f"SELECT id, name, latitude_deg, longitude_deg FROM `{TABLE_ID}` WHERE type = 'large_airport' AND iso_country = 'US' LIMIT 5"
airports_df = client.query(query).to_dataframe()

for index, row in airports_df.iterrows():
    try:
        # THE FIX: We MUST have "/points/" in the middle of the URL
        lat = row['latitude_deg']
        lon = row['longitude_deg']
        point_url = f"https://api.weather.gov{lat},{lon}"

        print(f"Checking: {row['name']} -> {point_url}")

        # 1. Get Forecast Metadata
        res = requests.get(point_url, headers=headers, timeout=10)
        res.raise_for_status()
        forecast_url = res.json()['properties']['forecast']

        # 2. Get the actual Forecast text
        forecast_res = requests.get(forecast_url, headers=headers, timeout=10)
        forecast_res.raise_for_status()

        # Grab the first available forecast period
        forecast_periods = forecast_res.json()['properties']['periods']
        forecast_text = forecast_periods[0]['detailedForecast']

        # 3. Generate the AI Alert
        prompt = f"Create a short aviation safety alert for {row['name']}. Weather: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": str(row['id']),
            "name": row['name'],
            "latitude": float(lat),
            "longitude": float(lon),
            "forecast": forecast_text,
            "ai_alert": response.text
        })
        print(f"✅ Success: {row['name']}")

        # Sleep to avoid hitting API rate limits
        time.sleep(1)

    except Exception as e:
        print(f"❌ Skipping {row['name']} due to error: {e}")

if not alerts_data:
    print("CRITICAL ERROR: List is still empty. Check the printed URLs above.")
else:
    print(f"\nDONE! Generated {len(alerts_data)} alerts.")

import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import time
import pandas as pd

# Initialize
vertexai.init(project=PROJECT_ID, location="us-central1")
model = GenerativeModel("gemini-1.0-pro")

headers = {'User-Agent': '(my-weather-app, myemail@example.com)'}
alerts_data = []

# Ensure we have the data
query = f"SELECT id, name, latitude_deg, longitude_deg FROM `{TABLE_ID}` WHERE type = 'large_airport' AND iso_country = 'US' LIMIT 5"
airports_df = client.query(query).to_dataframe()

print(f"Starting weather pull for {len(airports_df)} airports...")

for index, row in airports_df.iterrows():
    try:
        # We manually build the URL parts to prevent the concatenation error
        base_url = "https://api.weather.gov"
        endpoint = f"/points/{row['latitude_deg']},{row['longitude_deg']}"
        point_url = base_url + endpoint

        print(f"Checking: {row['name']}")
        print(f"URL: {point_url}") # This MUST show api.weather.gov/points/...

        # 1. Get Metadata
        res = requests.get(point_url, headers=headers, timeout=15)
        res.raise_for_status()
        forecast_url = res.json()['properties']['forecast']

        # 2. Get Forecast
        forecast_res = requests.get(forecast_url, headers=headers, timeout=15)
        forecast_res.raise_for_status()

        # Grab the first forecast period text
        periods = forecast_res.json()['properties']['periods']
        forecast_text = periods[0]['detailedForecast']

        # 3. Gemini Alert
        prompt = f"Create a short aviation safety alert for {row['name']}. Weather: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": str(row['id']),
            "name": row['name'],
            "latitude": float(row['latitude_deg']),
            "longitude": float(row['longitude_deg']),
            "forecast": forecast_text,
            "ai_alert": response.text
        })
        print(f"✅ Success: {row['name']}")
        time.sleep(1)

    except Exception as e:
        print(f"❌ Failed: {row['name']} | Error: {e}")

if not alerts_data:
    print("\nCRITICAL ERROR: No data collected. Verify the URL printed above has '/points/'.")
else:
    print(f"\nDONE! Successfully generated {len(alerts_data)} alerts.")

import vertexai
from vertexai.generative_models import GenerativeModel
import requests
import time
import pandas as pd

# Initialize Vertex AI
vertexai.init(project=PROJECT_ID, location="us-central1")

# Use current stable models for 2025
# 1.5-flash is now standard; if it fails, try 'gemini-1.5-pro'
model = GenerativeModel("gemini-2.5-flash")

headers = {'User-Agent': '(my-weather-app, myemail@example.com)'}
alerts_data = []

# Fetch airports
query = f"SELECT id, name, latitude_deg, longitude_deg FROM `{TABLE_ID}` WHERE type = 'large_airport' AND iso_country = 'US' LIMIT 5"
airports_df = client.query(query).to_dataframe()

print(f"Starting pull for {len(airports_df)} airports...")

for index, row in airports_df.iterrows():
    try:
        # THE FIX: Ensure "/points/" is between the domain and coordinates
        lat, lon = row['latitude_deg'], row['longitude_deg']
        point_url = f"https://api.weather.gov/points/{lat},{lon}"

        print(f"Requesting: {point_url}")

        # 1. Get Metadata
        res = requests.get(point_url, headers=headers, timeout=10)
        res.raise_for_status()
        forecast_url = res.json()['properties']['forecast']

        # 2. Get Actual Forecast
        forecast_res = requests.get(forecast_url, headers=headers, timeout=10)
        forecast_res.raise_for_status()

        # Access first forecast period safely
        forecast_text = forecast_res.json()['properties']['periods'][0]['detailedForecast']

        # 3. AI Generation
        prompt = f"Generate a short aviation safety alert for {row['name']}. Weather: {forecast_text}"
        response = model.generate_content(prompt)

        alerts_data.append({
            "airport_id": str(row['id']),
            "name": row['name'],
            "latitude": float(lat),
            "longitude": float(lon),
            "forecast": forecast_text,
            "ai_alert": response.text
        })
        print(f"✅ Success: {row['name']}")
        time.sleep(1) # Prevent rate limiting

    except Exception as e:
        print(f"❌ Failed: {row['name']} | {e}")

if alerts_data:
    print(f"\nDONE! {len(alerts_data)} alerts generated. Proceed to BigQuery load.")
else:
    print("\nCRITICAL: No data generated. Check API status in console.")

from google.cloud import bigquery

# Convert the list to a DataFrame
alerts_df = pd.DataFrame(alerts_data)

# Define the target table ID
alerts_table_id = f"{PROJECT_ID}.{DATASET_ID}.airport_alerts"

# Configure the load job
job_config = bigquery.LoadJobConfig(
    # Create the table if it doesn't exist, or overwrite if it does
    write_disposition="WRITE_TRUNCATE",
    autodetect=True,
)

# Load data
try:
    load_job = client.load_table_from_dataframe(
        alerts_df, alerts_table_id, job_config=job_config
    )
    load_job.result()  # Wait for the job to finish
    print(f"✅ SUCCESS: {len(alerts_df)} alerts loaded into {alerts_table_id}")
except Exception as e:
    print(f"❌ Error loading to BigQuery: {e}")

from kfp import dsl
from kfp import compiler

@dsl.component(packages_to_install=["google-cloud-bigquery", "google-cloud-aiplatform", "requests", "pandas"])
def aero_alerts_job(project_id: str, dataset_id: str):
    # Paste your Step 2 & 3 logic here (NWS API -> Gemini -> BQ)
    pass

@dsl.pipeline(name="aero-alerts-pipeline")
def pipeline(project_id: str, dataset_id: str):
    aero_alerts_job(project_id=project_id, dataset_id=dataset_id)

# Compile and Run
compiler.Compiler().compile(pipeline_func=pipeline, package_path="pipeline.yaml")

!pip install --upgrade kfp google-cloud-aiplatform

from kfp import dsl
from kfp import compiler

@dsl.component(packages_to_install=["google-cloud-bigquery", "google-cloud-aiplatform", "requests", "pandas"])
def aero_alerts_job(project_id: str, dataset_id: str):
    # Paste your Step 2 & 3 logic here (NWS API -> Gemini -> BQ)
    pass

@dsl.pipeline(name="aero-alerts-pipeline")
def pipeline(project_id: str, dataset_id: str):
    aero_alerts_job(project_id=project_id, dataset_id=dataset_id)

# Compile and Run
compiler.Compiler().compile(pipeline_func=pipeline, package_path="pipeline.yaml")