# -*- coding: utf-8 -*-
"""emergency_response_challenge2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/repositories/5b12d52b-db60-4eb7-83e1-ace3b5511ced
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS emergency_data
# OPTIONS(location="us");

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# LOAD DATA OVERWRITE emergency_data.response_times
# FROM FILES (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/emergency_calls_response_times.csv'],
#   skip_leading_rows = 1
# );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT * FROM emergency_data.response_times LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL emergency_data.response_model
# OPTIONS (
#   model_type = 'linear_reg',
#   input_label_cols = ['response_time']
# ) AS
# SELECT
#   *
# FROM
#   `emergency_data.response_times`
# WHERE
#   response_time IS NOT NULL;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.EVALUATE(MODEL emergency_data.response_model);

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.PREDICT(MODEL `emergency_data.response_model`,
#     (
#     SELECT
#       'Medical' AS call_type,
#       'High' AS priority,
#       42.3601 AS latitude,
#       -71.0589 AS longitude,
#       14 AS hour_of_day
#     UNION ALL
#     SELECT
#       'Fire' AS call_type,
#       'Medium' AS priority,
#       42.3500 AS latitude,
#       -71.1000 AS longitude,
#       2 AS hour_of_day
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.PREDICT(MODEL `emergency_data.response_model`,
#     (
#     SELECT
#       101 AS call_id,  -- Added dummy call_id
#       'Medical' AS call_type,
#       'High' AS priority,
#       42.3601 AS latitude,
#       -71.0589 AS longitude,
#       14 AS hour_of_day
#     UNION ALL
#     SELECT
#       102 AS call_id,  -- Added dummy call_id
#       'Fire' AS call_type,
#       'Medium' AS priority,
#       42.3500 AS latitude,
#       -71.1000 AS longitude,
#       2 AS hour_of_day
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.PREDICT(MODEL `emergency_data.response_model`,
#     (
#     SELECT
#       101 AS call_id,
#       CURRENT_TIMESTAMP() AS call_timestamp,
#       'Medical' AS call_type,
#       'High' AS priority,
#       42.3601 AS latitude,
#       -71.0589 AS longitude,
#       14 AS hour_of_day
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.PREDICT(MODEL `emergency_data.response_model`,
#     (
#     SELECT
#       * REPLACE(
#         'Medical' AS call_type,
#         'High' AS priority,
#         14 AS hour_of_day
#       )
#     FROM `emergency_data.response_times`
#     LIMIT 1
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   *
# FROM
#   ML.PREDICT(MODEL `emergency_data.response_model`,
#     (
#     SELECT
#       * EXCEPT(response_time) -- Remove the actual answer so the model can predict it
#     FROM `emergency_data.response_times`
#     LIMIT 1
#     )
#   );