# -*- coding: utf-8 -*-
"""fraud_training_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/repositories/6d647e88-2992-4fae-b73c-c811f2071df2
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS fraud_dataset
# OPTIONS(
# location="us",
# default_table_expiration_days=14 );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_detection (
#   type STRING,
#   name STRING,
#   weight FLOAT64
# );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# 
# LOAD DATA into fraud_dataset.fraud_detection
# FROM FILES (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/fraud_data_raw.csv'],
#   autodetect = true,
#   skip_leading_rows = 1
# );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# LOAD DATA OVERWRITE fraud_dataset.fraud_detection
# FROM FILES (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/fraud_data_raw.csv'],
#   skip_leading_rows = 1
# );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(Employment_Status, Device_Type),
#     IF(Employment_Status = 'Full-time', 1, 0) AS is_full_time,
#     IF(Employment_Status = 'Part-time', 1, 0) AS is_part_time,
#     IF(Employment_Status = 'Unemployed', 1, 0) AS is_unemployed,
#     IF(Device_Type = 'Mobile', 1, 0) AS is_mobile,
#     IF(Device_Type = 'Desktop', 1, 0) AS is_desktop
# FROM fraud_dataset.fraud_detection;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(age),
#     IF(age BETWEEN 18 AND 24, 1, 0) AS age_18_24,
#     IF(age BETWEEN 25 AND 34, 1, 0) AS age_25_34,
#     IF(age BETWEEN 35 AND 44, 1, 0) AS age_35_44,
#     IF(age >= 45, 1, 0) AS age_45_plus
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     *,
#     SAFE_DIVIDE(Income, Amount_Requested) AS income_to_amount_ratio
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# 
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     *,
#     DATE_DIFF(CURRENT_DATE(), last_assistance_date, DAY) AS time_since_previous_assistance
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     *,
#     DATE_DIFF(CURRENT_DATE(), CAST(Previous_Assistance_Date AS DATE), DAY) AS time_since_previous_assistance
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT column_name
# FROM fraud_dataset.INFORMATION_SCHEMA.COLUMNS
# WHERE table_name = 'fraud_data_modified';

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(is_fraud, has_prior_default),
#     CAST(is_fraud AS INT64) AS is_fraud_numeric,
#     CAST(has_prior_default AS INT64) AS has_prior_default_numeric
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(Previous_Assistance_Received, Supporting_Doc_Verified, Fraudulent),
#     CAST(Previous_Assistance_Received AS INT64) AS Previous_Assistance_Received_numeric,
#     CAST(Supporting_Doc_Verified AS INT64) AS Supporting_Doc_Verified_numeric,
#     CAST(Fraudulent AS INT64) AS Fraudulent_numeric
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT * EXCEPT(Previous_Assistance_Received),
# CAST(Previous_Assistance_Received AS INT64) AS Previous_Assistance_Received_numeric
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(Fraudulent),
#     -- Convert the main target column to 0 or 1
#     CAST(Fraudulent AS INT64) AS Fraudulent_numeric
# FROM fraud_dataset.fraud_data_modified;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE fraud_dataset.fraud_data_modified AS
# SELECT
#     * EXCEPT(Employment_Status, Device_Type, age, Previous_Assistance_Received, Supporting_Doc_Verified, Fraudulent),
# 
#     -- a. One-hot encode Employment_Status and Device_Type
#     IF(Employment_Status = 'Full-time', 1, 0) AS is_full_time,
#     IF(Employment_Status = 'Part-time', 1, 0) AS is_part_time,
#     IF(Device_Type = 'Mobile', 1, 0) AS is_mobile,
#     IF(Device_Type = 'Desktop', 1, 0) AS is_desktop,
# 
#     -- b. Bin age and one-hot encode
#     IF(age BETWEEN 18 AND 24, 1, 0) AS age_18_24,
#     IF(age BETWEEN 25 AND 34, 1, 0) AS age_25_34,
#     IF(age >= 35, 1, 0) AS age_35_plus,
# 
#     -- c. Income-to-Amount-Requested ratio
#     SAFE_DIVIDE(Income, Amount_Requested) AS income_to_amount_ratio,
# 
#     -- d. Time Since Previous Assistance
#     DATE_DIFF(CURRENT_DATE(), CAST(Previous_Assistance_Date AS DATE), DAY) AS Time_Since_Previous_Assistance,
# 
#     -- e. Change True/False fields to 1s and 0s
#     CAST(Previous_Assistance_Received AS INT64) AS Previous_Assistance_Received_numeric,
#     CAST(Supporting_Doc_Verified AS INT64) AS Supporting_Doc_Verified_numeric,
#     CAST(Fraudulent AS INT64) AS Fraudulent_numeric
# 
# FROM `fraud_dataset.fraud_detection`;