# -*- coding: utf-8 -*-
"""PubSubBonusChallenge4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/repositories/7f28fa56-cb1f-47d5-b7ba-208b61e3da0a
"""

from google.cloud import bigquery

project_id = "qwiklabs-gcp-01-bb0d31ab0812"

client = bigquery.Client(project=project_id)
dataset_id = f"{project_id}.flight_data"
table_id = f"{dataset_id}.transponder_messages"

# Create Dataset
dataset = bigquery.Dataset(dataset_id)
dataset.location = "US"
client.create_dataset(dataset, exists_ok=True)

# Define Schema
schema = [
    bigquery.SchemaField("MT", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("TT", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("SID", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("AID", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("Hex", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("FID", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("DMG", "DATE", mode="NULLABLE"),
    bigquery.SchemaField("TMG", "TIME", mode="NULLABLE"),
    bigquery.SchemaField("DML", "DATE", mode="NULLABLE"),
    bigquery.SchemaField("TML", "TIME", mode="NULLABLE"),
    bigquery.SchemaField("CS", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("Alt", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("GS", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("Trk", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("Lat", "FLOAT64", mode="NULLABLE"),
    bigquery.SchemaField("Lng", "FLOAT64", mode="NULLABLE"),
    bigquery.SchemaField("VR", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("Sq", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("Alrt", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("Emer", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("SPI", "INT64", mode="NULLABLE"),
    bigquery.SchemaField("Gnd", "INT64", mode="NULLABLE"),
]

table = bigquery.Table(table_id, schema=schema)
client.create_table(table, exists_ok=True)
print(f"Table {table_id} created.")

import time
from google.cloud import pubsub_v1
from google.cloud import bigquery

# Use your actual Project ID
project_id = "qwiklabs-gcp-01-bb0d31ab0812"
topic_name = "flight-transponder"
subscription_id = "flight-sub"

# Initialize clients
subscriber = pubsub_v1.SubscriberClient()
bq_client = bigquery.Client(project=project_id)
table_id = f"{project_id}.flight_data.transponder_messages"

# 1. Create or Get the Subscription
topic_path = f"projects/{project_id}/topics/{topic_name}"
subscription_path = subscriber.subscription_path(project_id, subscription_id)

try:
    subscriber.create_subscription(name=subscription_path, topic=topic_path)
    print(f"Subscription {subscription_id} created.")
except Exception as e:
    print(f"Subscription {subscription_id} already exists or error: {e}")

# 2. Define the Callback (Parsing Logic)
def callback(message):
    try:
        # Decode the CSV string and split by comma
        raw_data = message.data.decode("utf-8").split(",")

        # Column names must match the BigQuery schema exactly
        col_names = ["MT", "TT", "SID", "AID", "Hex", "FID", "DMG", "TMG", "DML", "TML",
                     "CS", "Alt", "GS", "Trk", "Lat", "Lng", "VR", "Sq", "Alrt", "Emer", "SPI", "Gnd"]

        # Map list to dict and handle empty strings/date formatting
        row = {}
        for i in range(len(col_names)):
            val = raw_data[i] if i < len(raw_data) and raw_data[i] != '' else None

            # Format dates: BigQuery needs YYYY-MM-DD (CSV has YYYY/MM/DD)
            if val and (col_names[i] == "DMG" or col_names[i] == "DML"):
                val = val.replace("/", "-")

            row[col_names[i]] = val

        # Insert row into BigQuery
        errors = bq_client.insert_rows_json(table_id, [row])
        if errors:
            print(f"Borequery Errors: {errors}")
        else:
            message.ack() # Acknowledge success

    except Exception as e:
        print(f"Failed to process message: {e}")

# 3. Start the Subscriber
streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
print(f"Listening for messages on {topic_path}... (Let this run for 2-3 minutes)")

# Keep the cell active for 3 minutes to collect data
try:
    streaming_pull_future.result(timeout=180)
except Exception:
    streaming_pull_future.cancel()
    print("\nSubscriber stopped. Data collection complete.")

import time
from google.cloud import pubsub_v1
from google.cloud import bigquery

# 1. Configuration
user_project_id = "qwiklabs-gcp-01-bb0d31ab0812"  # Your current project
source_project_id = "paul-leroy"                # The project hosting the data
topic_name = "flight-transponder"
subscription_id = "flight-sub"

# 2. Initialize clients
subscriber = pubsub_v1.SubscriberClient()
bq_client = bigquery.Client(project=user_project_id)
table_id = f"{user_project_id}.flight_data.transponder_messages"

# 3. Correct Topic Path (pointing to paul-leroy)
topic_path = f"projects/{source_project_id}/topics/{topic_name}"
subscription_path = subscriber.subscription_path(user_project_id, subscription_id)

# 4. Create or Get the Subscription in YOUR project
try:
    subscriber.create_subscription(name=subscription_path, topic=topic_path)
    print(f"Subscription {subscription_id} created successfully.")
except Exception as e:
    print(f"Subscription status: {e}")

# 5. Callback Logic (Same as before)
def callback(message):
    try:
        raw_data = message.data.decode("utf-8").split(",")
        col_names = ["MT", "TT", "SID", "AID", "Hex", "FID", "DMG", "TMG", "DML", "TML",
                     "CS", "Alt", "GS", "Trk", "Lat", "Lng", "VR", "Sq", "Alrt", "Emer", "SPI", "Gnd"]

        row = {}
        for i in range(len(col_names)):
            val = raw_data[i] if i < len(raw_data) and raw_data[i] != '' else None
            if val and (col_names[i] == "DMG" or col_names[i] == "DML"):
                val = val.replace("/", "-")
            row[col_names[i]] = val

        errors = bq_client.insert_rows_json(table_id, [row])
        if not errors:
            message.ack()
    except Exception as e:
        pass

# 6. Start the Subscriber
streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
print(f"Now listening to: {topic_path}...")

try:
    # Run for 180 seconds to collect enough data for visualization
    streaming_pull_future.result(timeout=180)
except Exception:
    streaming_pull_future.cancel()
    print("\nData collection complete.")

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   COUNT(*) as total_records
# FROM `qwiklabs-gcp-01-bb0d31ab0812.flight_data.transponder_messages`

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   ST_GEOGPOINT(Lng, Lat) as position,
#   Hex as aircraft_hex,
#   CS as callsign,
#   Alt as altitude
# FROM `qwiklabs-gcp-01-bb0d31ab0812.flight_data.transponder_messages`
# WHERE Lat IS NOT NULL AND Lng IS NOT NULL

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT
#   ST_GEOGPOINT(Lng, Lat) AS position,
# 
# FROM `qwiklabs-gcp-01-bb0d31ab0812.flight_data.transponder_messages`
# WHERE Lat IS NOT NULL AND Lng IS NOT NULL

