# -*- coding: utf-8 -*-
"""weather_data_Challenge3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/repositories/9560879b-f9c5-4dd4-a137-7d7540924bd9
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS weather_dataset
# OPTIONS(location="us");

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# LOAD DATA OVERWRITE weather_dataset.raw_weather
# FROM FILES (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv'],
#   skip_leading_rows = 1
# );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# SELECT * FROM weather_dataset.raw_weather LIMIT 5;

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-1.5-flash');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE weather_dataset.weather_with_reports AS
# SELECT
#   *,
#   ml_generate_text_result AS weather_report
# FROM
#   ML.GENERATE_TEXT(
#     MODEL `weather_dataset.gemini_model`,
#     (
#       SELECT
#         *,
#         CONCAT(
#           'Based on a temperature of ', temperature,
#           ' degrees, wind speed of ', wind_speed,
#           ' mph, and humidity of ', humidity,
#           '%, write a short, professional weather warning or report.'
#         ) AS prompt
#       FROM
#         `weather_dataset.raw_weather`
#     ),
#     STRUCT(
#       0.2 AS temperature,
#       250 AS max_output_tokens
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-1.5-flash-002');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-1.0-pro');

!gcloud services enable aiplatform.googleapis.com

!bq mk --connection --location=US --project_id=qwiklabs-gcp-01-bb0d31ab0812 --connection_type=CLOUD_RESOURCE gemini_conn

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-pro');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-2.0-flash');

!gcloud services enable aiplatform.googleapis.com

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION `us.gemini_conn`
# OPTIONS (ENDPOINT = 'gemini-1.5-pro');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE MODEL weather_dataset.gemini_model
# REMOTE WITH CONNECTION DEFAULT
# OPTIONS(ENDPOINT = 'gemini-2.5-flash');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE weather_dataset.weather_with_reports AS
# SELECT
#   *,
#   ml_generate_text_result AS weather_report
# FROM
#   ML.GENERATE_TEXT(
#     MODEL `weather_dataset.gemini_model`,
#     (
#       SELECT
#         *,
#         CONCAT(
#           'Based on a temperature of ', temperature_f,
#           ' degrees, wind speed of ', wind_speed_mph,
#           ' mph, and humidity of ', humidity_percent,
#           '%, write a short, professional weather warning or report.'
#         ) AS prompt
#       FROM
#         `weather_dataset.raw_weather`
#     ),
#     STRUCT(
#       0.2 AS temperature,
#       250 AS max_output_tokens
#     )
#   );

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# select * from weather_dataset.weather_with_reports

